alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
domains:
- domain: snail-tail.app.xericode.net
  type: PRIMARY
  zone: app.xericode.net
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
name: snail-tail-app
region: nyc
static_sites:
- build_command: npx @ionic/cli build --prod -- --base-href /
  catchall_document: index.html
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: krazkidd/snail-tail
  name: web
  output_dir: www
  source_dir: /
