alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
domains:
- domain: snail-tail.xericode.net
  type: PRIMARY
  zone: xericode.net
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: snail-tail
    match:
      path:
        prefix: /
name: snail-tail-app
region: nyc
static_sites:
- build_command: npx @ionic/cli build --prod -- --base-href /
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: krazkidd/snail-tail
  name: snail-tail
  output_dir: www
  source_dir: /
